# Building Multiple Linear Regression Model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

In [7]:
df = pd.read_csv("Synergix_data_preprocessed.csv")

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19631 entries, 0 to 19630
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Page_traffic                  19631 non-null  float64
 1   Unit_price                    19631 non-null  float64
 2   Units_sold                    19631 non-null  int64
 3   Segment                       19631 non-null  object
 4   1_Star_Rating                 19631 non-null  float64
 5   2_Star_Rating                 19631 non-null  float64
 6   3_Star_Rating                 19631 non-null  float64
 7   4_Star_Rating                 19631 non-null  float64
 8   5_Star_Rating                 19631 non-null  float64
 9   Image_Count                   19631 non-null  float64
 10  Bullet_Count                  19631 non-null  float64
 11  Title_Count                   19631 non-null  float64
 12  Description_Length            19631 non-null  float64
 13  num_unique_Search_Terms       19631 non-null  float64
 14  Organic Search Rank           19631 non-null  float64
 15  Num_of_Promotions             19631 non-null  float64
 16  Sum of Spend                  19631 non-null  float64
 17  Online_Clicks                 19631 non-null  float64
 18  Online_Cost                   19631 non-null  float64
 19  Online_Impressions            19631 non-null  float64
 20  num_unique_campaigns          19631 non-null  float64
 21  Clicks_video                  19631 non-null  float64
 22  Cost_video                    19631 non-null  float64
 23  Impressions_video             19631 non-null  float64
 24  num_unique_campaigns_offline  19631 non-null  float64
 25  Units_sold>1000               19631 non-null  int64
dtypes: float64(23), int64(2), object(1)
memory usage: 3.9+ MB

In [9]:
df = df.drop(columns=['Units_sold>1000'])
df.head()

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Num_of_Promotions,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline
0,5835.0,22.214389,2071,Skincare,99.0,72.0,194.0,453.0,3272.0,6.0,...,0.0,0.0,1271.0,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0
1,1881.0,11.870778,681,Skincare,118.0,73.0,200.0,430.0,3084.0,9.0,...,0.0,0.0,494.0,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0
2,2477.0,27.645714,875,Makeup,108.0,85.0,232.0,511.0,3402.0,10.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0
3,4087.0,16.896848,1396,Makeup,82.0,64.0,167.0,303.0,2058.0,5.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0
4,1446.0,16.357664,822,Hair Care,29.0,24.0,88.0,200.0,1221.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0

In [10]:
# One-hot encode the 'Segment' column
df_encoded = pd.get_dummies(df, columns=['Segment'], drop_first=True)

# Display the first few rows of the modified dataset
df_encoded.head()

,Page_traffic,Unit_price,Units_sold,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,Bullet_Count,...,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,2071,99.0,72.0,194.0,453.0,3272.0,6.0,6.0,...,1271.0,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0,0,1
1,1881.0,11.870778,681,118.0,73.0,200.0,430.0,3084.0,9.0,8.0,...,494.0,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0,0,1
2,2477.0,27.645714,875,108.0,85.0,232.0,511.0,3402.0,10.0,7.0,...,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,0
3,4087.0,16.896848,1396,82.0,64.0,167.0,303.0,2058.0,5.0,7.0,...,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,0
4,1446.0,16.357664,822,29.0,24.0,88.0,200.0,1221.0,0.0,8.0,...,0.0,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0,0,0

In [11]:
X = df_encoded.drop('Units_sold', axis = 1)
y = df_encoded['Units_sold']

In [12]:
import statsmodels.api as sm

In [13]:
# Fitting the regression model using the X features
X_with_const = sm.add_constant(X)
model_reduced = sm.OLS(y, X_with_const).fit()

# Display the summary of the refitted model
model_reduced.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.462
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     672.6
Date:                Thu, 26 Oct 2023   Prob (F-statistic):               0.00
Time:                        17:08:07   Log-Likelihood:            -1.4184e+05
No. Observations:               19631   AIC:                         2.837e+05
Df Residuals:                   19605   BIC:                         2.839e+05
Df Model:                          25
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          640.0706     23.171     27.624      0.000     594.654     685.487
Page_traffic                     0.1714      0.002     98.883      0.000       0.168       0.175
Unit_price                     -13.3813      0.327    -40.869      0.000     -14.023     -12.739
1_Star_Rating                    0.4008      0.269      1.491      0.136      -0.126       0.928
2_Star_Rating                    0.5902      0.522      1.131      0.258      -0.433       1.613
3_Star_Rating                    0.0452      0.218      0.207      0.836      -0.383       0.473
4_Star_Rating                   -0.2013      0.172     -1.174      0.241      -0.537       0.135
5_Star_Rating                    0.0260      0.017      1.494      0.135      -0.008       0.060
Image_Count                      7.2432      0.520     13.925      0.000       6.224       8.263
Bullet_Count                    -1.7502      4.024     -0.435      0.664      -9.638       6.138
Title_Count                      0.2161      0.124      1.737      0.082      -0.028       0.460
Description_Length               0.3421      0.053      6.431      0.000       0.238       0.446
num_unique_Search_Terms         -7.3758      0.982     -7.508      0.000      -9.301      -5.450
Organic Search Rank             -0.3875      0.220     -1.764      0.078      -0.818       0.043
Num_of_Promotions              -44.7122     10.788     -4.145      0.000     -65.858     -23.567
Sum of Spend                    -0.0125      0.019     -0.670      0.503      -0.049       0.024
Online_Clicks                   -0.1371      0.017     -8.101      0.000      -0.170      -0.104
Online_Cost                      0.0183      0.003      6.047      0.000       0.012       0.024
Online_Impressions              -0.0003   6.61e-05     -4.758      0.000      -0.000      -0.000
num_unique_campaigns            47.1743      2.424     19.461      0.000      42.423      51.926
Clicks_video                    -0.1003      0.011     -9.301      0.000      -0.121      -0.079
Cost_video                       0.0145      0.001     10.041      0.000       0.012       0.017
Impressions_video            -6.971e-05   7.95e-06     -8.773      0.000   -8.53e-05   -5.41e-05
num_unique_campaigns_offline    27.3258      4.211      6.489      0.000      19.072      35.580
Segment_Makeup                  77.7571      7.352     10.576      0.000      63.346      92.168
Segment_Skincare                68.1126      7.819      8.711      0.000      52.786      83.439
==============================================================================
Omnibus:                       87.383   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              116.332
Skew:                           0.054   Prob(JB):                     5.48e-26
Kurtosis:                       3.361   Cond. No.                     4.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Checking the VIF Scores

In [14]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [15]:
#function to calculate the VIF score
def calculate_vif(data):
    """Calculate VIF for a dataframe."""
    vif_data = pd.DataFrame()
    vif_data["Variable"] = data.columns
    vif_data["VIF"] = [variance_inflation_factor(data.values, i) for i in range(data.shape[1])]
    return vif_data

calculate_vif(X)

                        Variable         VIF
0                   Page_traffic    6.238345
1                     Unit_price    8.827610
2                  1_Star_Rating   82.714889
3                  2_Star_Rating  156.867547
4                  3_Star_Rating  202.676770
5                  4_Star_Rating  513.165763
6                  5_Star_Rating  231.315451
7                    Image_Count    3.193817
8                   Bullet_Count   63.892189
9                    Title_Count   33.721948
10            Description_Length   11.147435
11       num_unique_Search_Terms    5.006021
12           Organic Search Rank    3.975378
13             Num_of_Promotions    2.225613
14                  Sum of Spend    2.163706
15                 Online_Clicks   23.027784
16                   Online_Cost    9.590266
17            Online_Impressions   13.287097
18          num_unique_campaigns    5.872454
19                  Clicks_video  356.288733
20                    Cost_video  826.660945
21             Impressions_video  206.236694
22  num_unique_campaigns_offline   11.786276
23                Segment_Makeup    4.783921
24              Segment_Skincare    3.266871

# Removing Features with VIF Scores > 10

In [16]:
# Iteratively remove features with the highest VIF
VIF_threshold = 10
max_vif = float('inf')
while max_vif > VIF_threshold:
        # Calculate VIF
    vif_df = calculate_vif(X)
 
    #Finding the max values of vif scores
    max_vif = vif_df["VIF"].max()
    
    # If the maximum VIF is above the threshold, remove that variable
    if max_vif > VIF_threshold:
        remove = vif_df.sort_values("VIF", ascending=False).iloc[0]

        #Dropping columns from features simultaneously
        X.drop(remove["Variable"], axis=1, inplace = True)

# Display the features and their VIFs after the iterative removal
final_vif = calculate_vif(X)
final_vif.sort_values(by='VIF', ascending = False)

                        Variable       VIF
12             Impressions_video  9.286205
13  num_unique_campaigns_offline  8.565615
9                    Online_Cost  7.887754
1                     Unit_price  6.803903
10            Online_Impressions  5.979516
4             Description_Length  5.745783
11          num_unique_campaigns  5.378501
0                   Page_traffic  5.163783
5        num_unique_Search_Terms  4.807657
14                Segment_Makeup  4.031306
6            Organic Search Rank  3.785547
2                  5_Star_Rating  3.758746
3                    Image_Count  3.036648
15              Segment_Skincare  2.760112
7              Num_of_Promotions  2.215652
8                   Sum of Spend  2.116337

In [17]:
# Data for regression
X.shape, y.shape

((19631, 16), (19631,))

In [18]:
# Add a constant for the intercept term
X_with_const = sm.add_constant(X)

# Fit the regression model using statsmodels
model = sm.OLS(y, X_with_const).fit()

In [19]:
# Display the model summary
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.456
Method:                 Least Squares   F-statistic:                     1029.
Date:                Thu, 26 Oct 2023   Prob (F-statistic):               0.00
Time:                        17:08:24   Log-Likelihood:            -1.4194e+05
No. Observations:               19631   AIC:                         2.839e+05
Df Residuals:                   19614   BIC:                         2.840e+05
Df Model:                          16
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          659.1355     14.543     45.323      0.000     630.630     687.641
Page_traffic                     0.1693      0.002     99.116      0.000       0.166       0.173
Unit_price                     -13.6277      0.327    -41.664      0.000     -14.269     -12.987
5_Star_Rating                    0.0284      0.002     12.848      0.000       0.024       0.033
Image_Count                      7.2639      0.501     14.505      0.000       6.282       8.246
Description_Length               0.3960      0.041      9.682      0.000       0.316       0.476
num_unique_Search_Terms         -7.6729      0.968     -7.929      0.000      -9.570      -5.776
Organic Search Rank             -0.3761      0.220     -1.712      0.087      -0.807       0.054
Num_of_Promotions              -50.6304     10.811     -4.683      0.000     -71.821     -29.440
Sum of Spend                    -0.0245      0.019     -1.326      0.185      -0.061       0.012
Online_Cost                      0.0104      0.003      3.774      0.000       0.005       0.016
Online_Impressions              -0.0007   4.45e-05    -16.377      0.000      -0.001      -0.001
num_unique_campaigns            40.3387      2.331     17.305      0.000      35.770      44.908
Impressions_video            -8.217e-06    1.7e-06     -4.845      0.000   -1.15e-05   -4.89e-06
num_unique_campaigns_offline    28.9304      3.607      8.021      0.000      21.860      36.000
Segment_Makeup                  78.8128      7.306     10.788      0.000      64.493      93.132
Segment_Skincare                67.1476      7.848      8.556      0.000      51.765      82.530
==============================================================================
Omnibus:                      102.754   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.909
Skew:                           0.068   Prob(JB):                     1.13e-30
Kurtosis:                       3.387   Cond. No.                     2.83e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.83e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
X.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Organic Search Rank,Num_of_Promotions,Sum of Spend,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,3272.0,6.0,141.0,3.0,3.0,0.0,0.0,3102.448115,238075.0,6.0,3856872.0,2.0,0,1
1,1881.0,11.870778,3084.0,9.0,149.0,13.0,16.0,0.0,0.0,1723.716359,75868.0,2.0,0.0,0.0,0,1
2,2477.0,27.645714,3402.0,10.0,186.0,4.0,20.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1,0
3,4087.0,16.896848,2058.0,5.0,209.0,7.0,20.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1,0
4,1446.0,16.357664,1221.0,0.0,158.0,4.0,16.0,0.0,0.0,0.000000,0.0,0.0,7539723.0,2.0,0,0

# Removing Features with P-Values > 0.05

# Run all the above cell

In [22]:
#A quick look at the p-values
model.pvalues

const                           0.000000e+00
Page_traffic                    0.000000e+00
Unit_price                      0.000000e+00
5_Star_Rating                   1.244947e-37
Image_Count                     1.994809e-47
Description_Length              4.044449e-22
num_unique_Search_Terms         2.332403e-15
Organic Search Rank             8.683046e-02
Num_of_Promotions               2.842339e-06
Sum of Spend                    1.849751e-01
Online_Cost                     1.608493e-04
Online_Impressions              7.000289e-60
num_unique_campaigns            1.338118e-66
Impressions_video               1.274752e-06
num_unique_campaigns_offline    1.110912e-15
Segment_Makeup                  4.670519e-27
Segment_Skincare                1.251469e-17
dtype: float64

In [23]:
# Identify features with p-values greater than 0.05
features_to_remove = model.pvalues[model.pvalues > 0.05].index
#If constant has a p-value > 0.05, we are not removing it from our X features: {Reason}
if 'const' in features_to_remove:
    features_to_remove = features_to_remove.drop('const')
print(features_to_remove)

Index(['Organic Search Rank', 'Sum of Spend'], dtype='object')

In [24]:
# Drop those features
X = X.drop(columns=features_to_remove)
X.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Num_of_Promotions,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,3272.0,6.0,141.0,3.0,0.0,3102.448115,238075.0,6.0,3856872.0,2.0,0,1
1,1881.0,11.870778,3084.0,9.0,149.0,13.0,0.0,1723.716359,75868.0,2.0,0.0,0.0,0,1
2,2477.0,27.645714,3402.0,10.0,186.0,4.0,0.0,0.000000,0.0,0.0,0.0,0.0,1,0
3,4087.0,16.896848,2058.0,5.0,209.0,7.0,0.0,0.000000,0.0,0.0,0.0,0.0,1,0
4,1446.0,16.357664,1221.0,0.0,158.0,4.0,0.0,0.000000,0.0,0.0,7539723.0,2.0,0,0

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
X_scaled = scaler.fit_transform(X)

In [28]:
# Convert the scaled numpy array back to a pandas DataFrame
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

In [29]:
X_scaled_df.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Num_of_Promotions,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,1.703204,0.094899,1.243063,-0.168022,0.005376,-0.504854,-0.341256,0.843904,1.521245,2.460962,0.390454,0.587250,-1.086840,1.444183
1,-0.914797,-1.236958,1.101515,0.444920,0.136899,2.826504,-0.341256,0.127406,-0.025720,0.261051,-0.714274,-0.639296,-1.086840,1.444183
2,-0.520177,0.794244,1.340942,0.649235,0.745192,-0.171718,-0.341256,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
3,0.545828,-0.589795,0.329025,-0.372337,1.123320,0.827689,-0.341256,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
4,-1.202817,-0.659221,-0.301165,-1.393908,0.284862,-0.171718,-0.341256,-0.768373,-0.749271,-0.838904,1.445337,0.587250,-1.086840,-0.692433

In [30]:
# Add constant and fit the OLS model

X_scaled_const = sm.add_constant(X_scaled_df)

In [31]:
final_desc_model = sm.OLS(y, X_scaled_const).fit()

In [32]:
# Display the summary
print(final_desc_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.456
Method:                 Least Squares   F-statistic:                     1175.
Date:                Thu, 26 Oct 2023   Prob (F-statistic):               0.00
Time:                        17:08:40   Log-Likelihood:            -1.4194e+05
No. Observations:               19631   AIC:                         2.839e+05
Df Residuals:                   19616   BIC:                         2.840e+05
Df Model:                          14
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         1115.6042      2.385    467.699      0.000    1110.929    1120.280
Page_traffic                   255.5604      2.579     99.089      0.000     250.505     260.616
Unit_price                    -105.9307      2.540    -41.711      0.000    -110.909    -100.953
5_Star_Rating                   38.4900      2.889     13.322      0.000      32.827      44.153
Image_Count                     35.4762      2.451     14.474      0.000      30.672      40.280
Description_Length              24.3443      2.478      9.823      0.000      19.486      29.202
num_unique_Search_Terms        -24.0023      2.820     -8.512      0.000     -29.530     -18.475
Num_of_Promotions              -18.9101      2.411     -7.843      0.000     -23.636     -14.184
Online_Cost                     19.8167      5.315      3.729      0.000       9.399      30.234
Online_Impressions             -76.0310      4.664    -16.301      0.000     -85.173     -66.889
num_unique_campaigns            72.9615      4.235     17.229      0.000      64.661      81.262
Impressions_video              -28.9850      5.911     -4.904      0.000     -40.571     -17.399
num_unique_campaigns_offline    47.2023      5.882      8.025      0.000      35.673      58.731
Segment_Makeup                  39.3272      3.640     10.804      0.000      32.192      46.462
Segment_Skincare                31.5005      3.673      8.576      0.000      24.301      38.700
==============================================================================
Omnibus:                      103.126   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              138.507
Skew:                           0.068   Prob(JB):                     8.39e-31
Kurtosis:                       3.388   Cond. No.                         5.75
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [33]:
X_scaled_df.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Num_of_Promotions,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,1.703204,0.094899,1.243063,-0.168022,0.005376,-0.504854,-0.341256,0.843904,1.521245,2.460962,0.390454,0.587250,-1.086840,1.444183
1,-0.914797,-1.236958,1.101515,0.444920,0.136899,2.826504,-0.341256,0.127406,-0.025720,0.261051,-0.714274,-0.639296,-1.086840,1.444183
2,-0.520177,0.794244,1.340942,0.649235,0.745192,-0.171718,-0.341256,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
3,0.545828,-0.589795,0.329025,-0.372337,1.123320,0.827689,-0.341256,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
4,-1.202817,-0.659221,-0.301165,-1.393908,0.284862,-0.171718,-0.341256,-0.768373,-0.749271,-0.838904,1.445337,0.587250,-1.086840,-0.692433