In [1]:
#importing os library
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#changing the work directory
os.chdir('/Users/admin/Desktop/Synergyx Dataset')

In [3]:
#reading Pos_Data and checking the first 5 rows
pos = pd.read_excel("pos_sample.xlsx")
pos.head()

    SKU_ID  Page_traffic  Units_sold Segment
0  SKU1011        4119.0         697  Makeup
1  SKU1011        4074.0        1027  Makeup
2  SKU1011        4897.0        1037  Makeup
3  SKU1011        4783.0        1184  Makeup
4  SKU1011        3789.0         876  Makeup

In [4]:
# view the shape of the data
pos.shape

(3993, 4)

# Steps we will follow to build a model for doing prediction

1. We will begin with dividing the data set into train and valid.
2. Then we will perform mean based and rule based prediction
3. And finally we will evaluate models correctness using MAE

# Step 1: Divide the dataset

In [5]:
#import train_test_split to split data into pos_train and pos_valid
from sklearn.model_selection import train_test_split

In [6]:
#split the data into pos_train and pos_valid|
pos_train, pos_valid= train_test_split(pos, test_size = 0.2, random_state = 9)

In [7]:
#check the shape of train and validation data
pos_train.shape, pos_valid.shape

((3194, 4), (799, 4))

# Step 2: Perform Prediction (Mean Based Prediction)

In [8]:
#overall mean of Units_sold for train data and converting it into integers since units sold cannot be decimals
units_sold_mean = int(pos_train['Units_sold'].mean())

In [9]:
#creating a new column- "Pred_Mean_Units_Sold" in the pos_valid dataframe and assigning the mean of Units_sold from train data 
pos_valid['Pred_Mean_Units_Sold']= units_sold_mean
pos_valid.head()

       SKU_ID  Page_traffic  Units_sold    Segment  Pred_Mean_Units_Sold
2137   SKU252        3202.0        1303   Skincare                  1157
118   SKU1056        4423.0        1586     Makeup                  1157
903    SKU145        4562.0        1522  Hair Care                  1157
1966   SKU199        4775.0        1495     Makeup                  1157
2335   SKU271        2953.0        1138     Makeup                  1157

# Step 3: Evaluate Prediction

In [10]:
#import mean_absolute_error from sklearn.metrics
from sklearn.metrics import mean_absolute_error

In [11]:
#MAE of overall Units_sold mean from pos_train and actual values of 'Units_sold' from pos_valid
mean_absolute_error(pos_valid['Units_sold'], pos_valid['Pred_Mean_Units_Sold'])

307.0475594493116

# Approach 2 (Rule Based Prediction)

# Step 2: Perform Prediction

In [12]:
#calculate mean of Units_sold for pos_train by segment
mean_units_sold_by_segment = pos_train.groupby(by = 'Segment').mean()["Units_sold"].astype(int)
mean_units_sold_by_segment

/var/folders/_0/4jdzsn4d7r5ftym_wrzdv1cr0000gn/T/ipykernel_48959/3062489265.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mean_units_sold_by_segment = pos_train.groupby(by = 'Segment').mean()["Units_sold"].astype(int)

Segment
Hair Care    1166
Makeup       1152
Skincare     1161
Name: Units_sold, dtype: int64

In [13]:
#creating a new column- "Pred_Segment_Mean_Units_Sold" in the pos_valid dataframe and assigning the mean 
pos_valid['Pred_Segment_Mean_Units_Sold'] = pos_valid['Segment'].map(mean_units_sold_by_segment)
#view first 10 rows of pos_valid
pos_valid.head(10)

,SKU_ID,Page_traffic,Units_sold,Segment,Pred_Mean_Units_Sold,Pred_Segment_Mean_Units_Sold
2137,SKU252,3202.0,1303,Skincare,1157,1161
118,SKU1056,4423.0,1586,Makeup,1157,1152
903,SKU145,4562.0,1522,Hair Care,1157,1166
1966,SKU199,4775.0,1495,Makeup,1157,1152
2335,SKU271,2953.0,1138,Makeup,1157,1152
3339,SKU786,3216.0,1038,Makeup,1157,1152
595,SKU1266,4506.0,1125,Skincare,1157,1161
2241,SKU264,8062.0,1723,Skincare,1157,1161
310,SKU1099,2081.0,1247,Makeup,1157,1152
1987,SKU199,3274.0,1564,Makeup,1157,1152

# Step 3: Evaluate Prediction

In [14]:
#MAE of segment wise Units_sold mean from pos_train and actual values of 'Units_sold' from pos_valid
mean_absolute_error(pos_valid['Units_sold'],pos_valid['Pred_Segment_Mean_Units_Sold'])

306.4267834793492